#!/usr/bin/env bash
# Builds and deploys the SAM stack, then publishes the frontend to S3/CloudFront
# with the freshly deployed API/Cognito settings baked into js/config.js.
set -euo pipefail

STACK_NAME="${STACK_NAME:-expense-splitter}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export SAM_CLI_TELEMETRY=0

# Homebrew's python@3.14 bottle on macOS ships a pyexpat.so linked against a
# newer libexpat symbol than the system /usr/lib/libexpat.1.dylib provides,
# which breaks every `sam` subcommand with an ImportError. Point dyld at
# Homebrew's own libexpat if present; harmless no-op otherwise/on other OSes.
if command -v brew >/dev/null 2>&1; then
  expat_lib="$(brew --prefix expat 2>/dev/null || true)/lib"
  if [ -d "$expat_lib" ]; then
    export DYLD_LIBRARY_PATH="${expat_lib}:${DYLD_LIBRARY_PATH:-}"
    export DYLD_FALLBACK_LIBRARY_PATH="${expat_lib}:${DYLD_FALLBACK_LIBRARY_PATH:-}"
  fi
fi

echo "==> Building SAM application"
sam build --template-file "$ROOT_DIR/template.yaml"

echo "==> Deploying stack: $STACK_NAME"
# "No changes to deploy" is a non-zero exit from `sam deploy` but not a real
# failure (it just means the backend is already up to date) - don't let it
# abort the script before the frontend gets synced below.
deploy_output=$(sam deploy --stack-name "$STACK_NAME" --resolve-s3 --capabilities CAPABILITY_IAM --no-confirm-changeset 2>&1) \
  || { echo "$deploy_output" | grep -qi "No changes to deploy" || { echo "$deploy_output"; exit 1; }; }
echo "$deploy_output"

echo "==> Reading stack outputs"
outputs=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" \
  --query "Stacks[0].Outputs" --output json)

get_output() {
  echo "$outputs" | python3 -c "import sys,json; d=json.load(sys.stdin); print(next(o['OutputValue'] for o in d if o['OutputKey']=='$1'))"
}

API_URL=$(get_output ApiUrl)
USER_POOL_ID=$(get_output UserPoolId)
USER_POOL_CLIENT_ID=$(get_output UserPoolClientId)
SITE_BUCKET=$(get_output SiteBucketName)
SITE_WEBSITE_URL=$(get_output SiteWebsiteUrl)
REGION=$(aws configure get region)

echo "==> Writing frontend/js/config.js"
cat > "$ROOT_DIR/frontend/js/config.js" <<EOF
// Auto-generated by scripts/deploy.sh - do not edit by hand.
window.APP_CONFIG = {
  API_URL: "${API_URL}",
  USER_POOL_ID: "${USER_POOL_ID}",
  USER_POOL_CLIENT_ID: "${USER_POOL_CLIENT_ID}",
  REGION: "${REGION}",
};
EOF

echo "==> Syncing frontend to s3://$SITE_BUCKET"
aws s3 sync "$ROOT_DIR/frontend" "s3://$SITE_BUCKET" --delete --exclude ".DS_Store"

echo
echo "Deployment complete."
echo "  Live site:   ${SITE_WEBSITE_URL}"
echo "  API URL:     ${API_URL}"
echo "  User Pool:   ${USER_POOL_ID}"
