// Auto-generated by scripts/deploy.sh - do not edit by hand.
window.APP_CONFIG = {
  API_URL: "https://tz9ifto2oe.execute-api.us-east-1.amazonaws.com",
  USER_POOL_ID: "us-east-1_VWTXkvKlp",
  USER_POOL_CLIENT_ID: "50f893qfb51kgpebos2oh53qpv",
  REGION: "us-east-1",
};
